spring.application.name=03_community

# 포트 번호 변경
server.port=8989

# JSP view 경로 설정 (ViewResolver)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# DB 접속 정보
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##SPRING
spring.datasource.password=SPRING
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 파일 업로드 설정
# 업로드 파일 1개 최대 크기
spring.servlet.multipart.max-file-size=10MB
# 업로드 요청의 최대 크기
spring.servlet.multipart.max-request-size=50MB